### ISSUE TITLE
Incorrect node paths

### ISSUE THREAD

**Issue by zhukoven** [garciadelcastillo/ViveTrack-Dynamo#1]
ViveTrack-Dynamo package has unresolved nodes because of the incorrect paths (see the screenshot attached).

![dynamo vive track error](https://user-images.githubusercontent.com/27201628/43529830-cbb149b4-95b4-11e8-901b-e83e5002c99c.png)

**Comment by garciadelcastillo** [comment]
Good catch @zhukoven! 

That's actually not a path problem, but I changed the architecture of the controller components, and forgot to update the sample files... 

Can you try replacing "Controller1" and "Controller2" by the new "Controller" component, and same for lighthouses? It should probably work. 

I'll update sample files and reupload.

**Comment by garciadelcastillo** [comment]
Published new package with fixed sample file

**Comment by zhukoven** [comment]
@garciadelcastillo, great, thanks! Now it works in sample files without replacements.

**Comment by garciadelcastillo** [comment]
Cool. [Tweet me](https://twitter.com/garciadelcast) if you make something cool with it!
