### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by brunotux** [garciadelcastillo/ViveTrack-Dynamo#2]
Hi,
after a short time, I get an error. System.AccessViolationException. In the openvr_api.cs file, line:

FnTable.GetDeviceToAbsoluteTrackingPose(eOrigin, fPredictedSecondsToPhotonsFromNow, pTrackedDevicePoseArray, (uint)pTrackedDevicePoseArray.Length);

“An attempt was made to read or write in the protected memory”

**Comment by garciadelcastillo** [comment]
Mmm, that looks like a problem with the OpenVR library used by the package, not sure how to work around that. 
Are you using the compiled package or running your own build? 
I am planning on updating the core library sometime soon, that might solve the problem.

**Comment by brunotux** [comment]
I'm running my own build.
I'm trying to run it without dynamo as a plugin. In Revit and Navisworks. Everything works fine for a few minutes an then it crashes.

**Comment by garciadelcastillo** [comment]
I guess then that's a problem with the runtime you are using to run the wrapped core OpenVR. I would suggest you try running it with the newer version, see if it is more stable.
